import { Car } from "./car";
export const CARLIST:Car[]=[
    {
      "id": 1,
      "image": "toyota-corolla.jpg",
      "marque": "Toyota",
      "model": "Corolla",
      "typecar": "Berline",
      "version": 2023,
      "datesortie": "2023-01-01",
      "enginetype": "Essence",
      "taille": "Moyenne",
      "poids": "1300kg",
      "empathement": 2700
    },
    {
      "id": 2,
      "image": "honda-civic.jpg",
      "marque": "Honda",
      "model": "Civic",
      "typecar": "Berline",
      "version": 2022,
      "datesortie": "2022-06-01",
      "enginetype": "Diesel",
      "taille": "Moyenne",
      "poids": "1400kg",
      "empathement": 2750
    },
    {
      "id": 3,
      "image": "bmw-x5.jpg",
      "marque": "BMW",
      "model": "X5",
      "typecar": "SUV",
      "version": 2023,
      "datesortie": "2023-03-10",
      "enginetype": "Essence",
      "taille": "Grande",
      "poids": "2000kg",
      "empathement": 3000
    },
    {
      "id": 4,
      "image": "audi-a3.jpg",
      "marque": "Audi",
      "model": "A3",
      "typecar": "Berline",
      "version": 2021,
      "datesortie": "2021-05-15",
      "enginetype": "Essence",
      "taille": "Moyenne",
      "poids": "1500kg",
      "empathement": 2600
    },
    {
      "id": 5,
      "image": "ford-mustang.jpg",
      "marque": "Ford",
      "model": "Mustang",
      "typecar": "Coupé",
      "version": 2022,
      "datesortie": "2022-07-20",
      "enginetype": "Essence",
      "taille": "Grande",
      "poids": "1700kg",
      "empathement": 2800
    },
    {
      "id": 6,
      "image": "mercedes-c-class.jpg",
      "marque": "Mercedes-Benz",
      "model": "C-Class",
      "typecar": "Berline",
      "version": 2023,
      "datesortie": "2023-02-25",
      "enginetype": "Diesel",
      "taille": "Moyenne",
      "poids": "1600kg",
      "empathement": 2750
    },
    {
      "id": 7,
      "image": "porsche-911.jpg",
      "marque": "Porsche",
      "model": "911",
      "typecar": "Coupé",
      "version": 2021,
      "datesortie": "2021-08-10",
      "enginetype": "Essence",
      "taille": "Petite",
      "poids": "1450kg",
      "empathement": 2400
    },
    {
      "id": 8,
      "image": "tesla-model-s.jpg",
      "marque": "Tesla",
      "model": "Model S",
      "typecar": "Berline",
      "version": 2023,
      "datesortie": "2023-04-01",
      "enginetype": "Électrique",
      "taille": "Grande",
      "poids": "2000kg",
      "empathement": 2900
    },
    {
      "id": 9,
      "image": "chevrolet-camaro.jpg",
      "marque": "Chevrolet",
      "model": "Camaro",
      "typecar": "Coupé",
      "version": 2022,
      "datesortie": "2022-06-30",
      "enginetype": "Essence",
      "taille": "Grande",
      "poids": "1600kg",
      "empathement": 2600
    },
    {
      "id": 10,
      "image": "land-rover-defender.jpg",
      "marque": "Land Rover",
      "model": "Defender",
      "typecar": "4x4",
      "version": 2023,
      "datesortie": "2023-05-10",
      "enginetype": "Diesel",
      "taille": "Grande",
      "poids": "2200kg",
      "empathement": 3100
    }
  ]
  